services:
  bg-web-api:
    build: ./
    container_name: bg-web-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      JWTKEY: DhOrZJxIZY6fDu8u2hK30yN6LgX6GgYnJMsXcbsYQKgNwacVpa2ZxiuDRUC2CIBLcY3Y5N7TOnL
      JWTISSUER: http://localhost:8080
      JWTAUDIENCE: http://localhost:8080
      DB_CONNECTION: Host=db_postgres;Username=postgres;Password=postgres;Database=bg_test;
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db_postgres
  db_postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bg_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
networks:
  app-network: